name: Build lua-llthreads2 for Win32 static

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-2022
    defaults:
      run:
        shell: pwsh

    steps:
      - name: Checkout lua-llthreads2
        uses: actions/checkout@v4
        with:
          repository: fiendish/lua-llthreads2
          path: lua-llthreads2
          submodules: recursive

      - name: Checkout LuaJIT
        uses: actions/checkout@v4
        with:
          repository: fiendish/LuaJIT
          ref: v2.1
          path: lua-llthreads2/LuaJIT
          submodules: recursive

      - name: Download prebuilt lua51.lib
        working-directory: lua-llthreads2
        run: |
          Invoke-WebRequest 'https://github.com/fiendish/LuaJIT-build/releases/download/latest/lua51.lib' -OutFile 'lua51.lib'

      - name: Set up MSVC x86 build environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x86

      - name: Build lua-llthreads2
        working-directory: lua-llthreads2
        run: |
          cl /nologo /MT /O2 -c /Fo:l52util.obj -ILuaJIT\src src\l52util.c -DLLTHREAD_MODULE_NAME=llthreads2
          cl /nologo /MT /O2 -c /Fo:llthread.obj -ILuaJIT\src src\llthread.c -DLLTHREAD_MODULE_NAME=llthreads2
          link -dll -export:luaopen_llthreads2 -out:llthreads2.dll lua51.lib l52util.obj llthread.obj kernel32.lib

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: lua-llthreads2-win32
          path: lua-llthreads2/llthreads2.dll

      - name: Create or update "latest" release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest
          files: lua-llthreads2/llthreads2.dll
          prerelease: false
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
